- name: Create user
  hosts: all
  become: yes
  tasks:
    - name: Create user Hadoop
      import_role:
        name: create-user
      vars:
        user_name: hadoop

- name: Fetch public key from hadoop
  hosts: localhost
  become: true
  vars:
       user_name: hadoop
       user_home: /home/{{ user_name }}
  tasks:
    - name: Copy public key
      fetch:
        src: "{{ user_home }}/.ssh/id_rsa.pub"
        dest: "~/hadoop.pub"
        flat: true

- name: Fetch public key from hadoop server
  hosts: hadoopgrp
  become: true
  vars:
       user_name: hadoop
       user_home: /home/{{ user_name }}
  tasks:
    - name: Copy public key
      fetch:
        src: "{{ user_home }}/.ssh/id_rsa.pub"
        dest: "~/hadoop-server.pub"
        flat: true

- name: Set public key of hadoop
  hosts: all
  become: true
  vars:
       user_name: hadoop
       user_home: /home/{{ user_name }}
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', '~/hadoop-server.pub') }}"
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', '~/hadoop.pub') }}"
  - name: Restart SSH
    service:
      name: sshd
      state: restarted